# GitHub Labeler configuration for PRs
# https://github.com/actions/labeler

labeler-automation:
  - changed-files:
      - any: ['.github/**/*']

linting:
  - changed-files:
      - any: ['*.py', '**/*.py']

shell:
  - changed-files:
      - any: ['*.sh', '**/*.sh']

mac:
  - changed-files:
      - any: ['llm-server-mac', '**/llm-server-mac*']

windows:
  - changed-files:
      - any: ['llm-server-windows.py', '**/llm-server-windows*']

linux:
  - changed-files:
      - any: ['llm-server', '**/llm-server']
